packages:
  - "packages/*"

catalog:
  rimraf: ^6.0.1
  rolldown: 1.0.0-beta.37
  typescript: ^5.8.2
  "@biomejs/biome": ^2.2.4
  "@microsoft/api-extractor": ^7.52.13
  "@types/picomatch": ^4.0.2
  "@types/node": ^22.8.1

  esbuild: ^0.25.10
  picomatch: ^4.0.3