packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.4
  '@microsoft/api-extractor': ^7.52.13
  '@types/node': ^22.8.1
  '@types/picomatch': ^4.0.2
  esbuild: ^0.25.10
  picomatch: ^4.0.3
  rimraf: ^6.0.1
  rolldown: 1.0.0-rc.4
  typescript: ^5.8.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
