/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  sourcemap?: string
}
export declare function sum(a: number, b: number): number
export declare function transformCode(code: string, filePath: string): TransformOutput | null
