/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function transformCode(options: TransformOptions, cssPreprocessor?: (arg: string) => string | undefined | null): TransformOutput | null

export interface TransformOptions {
  code: string
  filePath: string
  cssOutDir: string
}

export interface TransformOutput {
  code: string
  sourcemap?: string
}
