
[package]
authors = ["akzhy <hi@akzhy.com>"]
edition = "2021"
name = "core"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
cssparser = "0.35.0"
indexmap = "2.11.1"
lightningcss = { version = "1.0.0-alpha.67", features = ["browserslist"] }
napi = "3.0.0"
napi-derive = "3.0.0"
once_cell = "1.20.2"
oxc = {version = "0.93.0", features = ["semantic", "ast_visit", "codegen"]}
regex = "1.11.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
