/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Theme {
  breakpoints: Record<string, string>
  prefix?: string
}

export declare function transformCode(code: string, filePath: string, options: TransformOptions, cssPreprocessor?: (arg: string) => string | undefined | null): TransformOutput | null

export interface TransformOptions {
  cssOutDir: string
  classNameList?: Array<string>
  useTheme?: boolean
  theme?: Theme
}

export interface TransformOutput {
  code: string
  sourcemap?: string
  css: string
}
