/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function transformCode(code: string, filePath: string, options: TransformOptions, cssPreprocessor?: (arg: string) => string | undefined | null): TransformOutput | null

export interface TransformOptions {
  cssOutDir: string
  classNameList?: Array<string>
}

export interface TransformOutput {
  code: string
  sourcemap?: string
}
