/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Log entry structure that will be sent to the JS side */
export interface LogEntry {
  message: string
  level:  'error' | 'warn' | 'info'
}

/** Log level enum that matches your required structure */
export declare const enum LogLevel {
  Error = 0,
  Warn = 1,
  Info = 2
}

export interface Theme {
  breakpoints: Record<string, string>
  prefix?: string
}

export declare function transformCode(code: string, filePath: string, options: TransformOptions, cssPreprocessor?: (arg: string) => string | undefined | null): TransformOutput | null

export interface TransformOptions {
  cssOutDir: string
  classNameList?: Array<string>
  useTheme?: boolean
  theme?: Theme
  appendTimestampToCssFile?: boolean
}

export interface TransformOutput {
  code: string
  sourcemap?: string
  css: string
  logs: Array<LogEntry>
  generatedCssName?: string
}
